---
title: "My Spotify Data"
author: "Silva Patrick"
format: revealjs
editor: 
  markdown: 
    wrap: 72
---

```{r include=FALSE}
renv::activate()
```

```{r include=FALSE}
library(tidyverse)
library(spotifyr)
library(ggradar)
```

```{r include=FALSE}
theme_set(theme_minimal(base_size = 14))

artists_af <- read_csv("data/top_artists_with_audio_features.csv")
hist2023 <- read.csv("data/Streaming_History_2023.csv")
raw <- read.csv("data/Streaming_2023_Raw.csv")

artists_genre <- artists_af |>
  select(artist_name, genres) |>
  distinct()

data <- hist2023 |>
  filter(master_metadata_album_artist_name %in% pull(artists_genre, artist_name)) |>
  left_join(artists_genre, 
            by = join_by(master_metadata_album_artist_name == artist_name),
            multiple = "all")

top_genres <- data |>
  count(genres, sort = TRUE) |>
  head(10) |>
  pull(genres)

platform_colors <- c("android" = "#A4C639", "windows" = "#3778BF",
                     "ios" = "#7D7D7D", "osx" = "#A6109F")
```

------------------------------------------------------------------------

```{r}
hist2023 |>
  mutate(month = month(date)) |>
  count(month, platform) |>
  ggplot(aes(x = month, y = n, fill = platform)) +
  geom_col() +
  scale_fill_manual(values = platform_colors) +
  labs(title = "How many songs did I listen on each platform each month?",
       y = element_blank(),
       x = element_blank()) +
  theme(axis.text.x = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank())
```

------------------------------------------------------------------------

```{r}
hist2023 |>
  mutate(month = month(date),
         day = day(date),
         wday = wday(date, label = TRUE),
         hour = hour(hms(time))) |>
  filter(month == 11 & day <= 19 & day >= 13) |>
  count(wday, hour, platform) |>
  ggplot(aes(x = hour, y = wday, colour = platform)) +
  geom_point(aes(size = 8)) +
  scale_color_manual(values = platform_colors) +
  labs(title = "Spotify activity during the week of the 13/11 - 19/11",
       y = element_blank(),
       x = element_blank()) +
  theme(legend.position = "none") + 
  scale_x_continuous(breaks = seq(0, 23, 1))
```

------------------------------------------------------------------------

```{r}
hist2023 |>
  mutate(month = month(date),
         day = day(date),
         wday = wday(date, label = TRUE),
         hour = hour(hms(time))) |>
  filter(month == 11 & day <= 26 & day >= 20) |>
  count(wday, hour, platform) |>
  ggplot(aes(x = hour, y = wday, colour = platform)) +
  geom_point(aes(size = 8)) +
  scale_color_manual(values = platform_colors) +
  labs(title = "Spotify activity during the week of the 20/11 - 26/11",
       y = element_blank(),
       x = element_blank()) +
  theme(legend.position = "none") + 
  scale_x_continuous(breaks = seq(0, 23, 1))
```

------------------------------------------------------------------------

```{r}
data |>
  filter(genres %in% top_genres) |>
  ggplot(aes(y = fct_rev(fct_infreq(genres)), fill = genres)) +
  geom_bar() +
  labs(title = "Genres I listened to most in 2023",
       subtitle = "(and their count)",
       y = element_blank(),
       x = element_blank()) +
  scale_fill_manual(values=c("j-rock"="red", "rock"="red",
                             "alternative rock" = "red")) +
  theme(legend.position = "none")
```

------------------------------------------------------------------------

```{r}
artists_af |>
  filter(artist_name == "Cocteau Twins") |>
  select(album_name, danceability, energy, mode, speechiness, acousticness,
         instrumentalness, liveness, valence) |>
  group_by(album_name) |>
  summarize(across(everything(), list(mean = mean))) |>
  ggradar(plot.legend = FALSE, 
          fill = TRUE, fill.alpha = 1,
          values.radar = element_blank(),
          group.point.size = 0,
          axis.labels = c('', '', '' , '', '', '', '', ''),
          plot.extent.x.sf = 1,
          plot.extent.y.sf = 1,
          group.line.width = 1,
          group.colours = (c("Victorialand" = "#3C4266",
                             "The Moon and the Melodies" = "#3c4266",
                             "Garlands" = "#e78558",
                             "Head Over Heels" = "#e78558"))) +
  facet_wrap(~album_name, ncol=4) + 
  theme(strip.background = element_blank(),
       strip.text.x = element_blank()) +
  labs(title = "What defines Rock and its subgenres?",
       subtitle = "A look at the audio features of the different albums of Cocteau Twins (Alt. Rock)") +
  theme(plot.title = element_text(size = 19, hjust = 0.5),
        plot.subtitle = element_text(size = 10, hjust = 0.5))
```

------------------------------------------------------------------------

```{r}
artists_af |>
  filter(artist_name == "Talking Heads") |>
  select(album_name, danceability, energy, mode, speechiness, acousticness,
         instrumentalness, liveness, valence) |>
  group_by(album_name) |>
  summarize(across(everything(), list(mean = mean))) |>
  ggradar(plot.legend = FALSE, 
          fill = TRUE, fill.alpha = 1,
          values.radar = element_blank(),
          group.point.size = 0,
          axis.labels = c('', '', '' , '', '', '', '', ''),
          plot.extent.x.sf = 1,
          plot.extent.y.sf = 1,
          group.line.width = 1,
          group.colours = (c("#6C6C6C"))) +
  facet_wrap(~album_name, ncol=4) + 
  theme(strip.background = element_blank(),
        strip.text.x = element_blank()) +
  labs(title = "What defines Rock and its subgenres?",
       subtitle = "A look at the audio features of the different albums of Talking Heads (Alt. Rock & Rock)") +
  theme(plot.title = element_text(size = 19, hjust = 0.5),
        plot.subtitle = element_text(size = 10, hjust = 0.5))
```

------------------------------------------------------------------------

```{r}
artists_af |>
  filter(artist_name == "The Beatles") |>
  filter(str_detect(album_name, "Deluxe", negate = TRUE)) |>
  filter(str_detect(album_name, "Live", negate = TRUE)) |>
  select(album_name, danceability, energy, mode, speechiness, acousticness,
         instrumentalness, liveness, valence) |>
  group_by(album_name) |>
  summarize(across(everything(), list(mean = mean))) |>
  ggradar(plot.legend = FALSE, 
          fill = TRUE, fill.alpha = 1,
          values.radar = element_blank(),
          group.point.size = 0,
          axis.labels = c('', '', '' , '', '', '', '', ''),
          plot.extent.x.sf = 1,
          plot.extent.y.sf = 1,
          group.line.width = 1,
          group.colours = (c("Yellow Submarine (Remastered)" = "#FBC01A"))) +
  facet_wrap(~album_name, ncol=5) + 
  theme(strip.background = element_blank(),
        strip.text.x = element_blank()) +
  labs(title = "What defines Rock and its subgenres?",
       subtitle = "A look at the audio features of the different albums of The Beatles (Rock)") +
  theme(plot.title = element_text(size = 19, hjust = 0.5),
        plot.subtitle = element_text(size = 10, hjust = 0.5))
```

------------------------------------------------------------------------

```{r}
artists_af |>
  filter(artist_name == "Fishmans") |>
  select(album_name, danceability, energy, mode, speechiness, acousticness,
         instrumentalness, liveness, valence) |>
  group_by(album_name) |>
  summarize(across(everything(), list(mean = mean))) |>
  ggradar(plot.legend = FALSE, 
          fill = TRUE, fill.alpha = 1,
          values.radar = element_blank(),
          group.point.size = 0,
          axis.labels = c('', '', '' , '', '', '', '', ''),
          plot.extent.x.sf = 1,
          plot.extent.y.sf = 1,
          group.line.width = 1,
          group.colours = (c("LONG SEASON" = "#E9967A"))) +
  facet_wrap(~album_name, ncol=5) + 
  theme(strip.background = element_blank(),
        strip.text.x = element_blank()) +
  labs(title = "What defines Rock and its subgenres?",
       subtitle = "A look at the audio features of the different albums of Fishmans (J-Rock)") +
  theme(plot.title = element_text(size = 19, hjust = 0.5),
        plot.subtitle = element_text(size = 10, hjust = 0.5))
```

------------------------------------------------------------------------

```{r}
artists_af |>
  filter(artist_name == "Kendrick Lamar") |>
  select(album_name, danceability, energy, mode, speechiness, acousticness,
         instrumentalness, liveness, valence) |>
  group_by(album_name) |>
  summarize(across(everything(), list(mean = mean))) |>
  ggradar(plot.legend = FALSE, 
          fill = TRUE, fill.alpha = 1,
          values.radar = element_blank(),
          group.point.size = 0,
          axis.labels = c('', '', '' , '', '', '', '', ''),
          plot.extent.x.sf = 1,
          plot.extent.y.sf = 1,
          group.line.width = 1,
          group.colours = (c("#6C6C6C"))) +
  facet_wrap(~album_name, ncol=4) + 
  theme(strip.background = element_blank(),
        strip.text.x = element_blank()) +
  labs(title = "What defines Rock and its subgenres?",
       subtitle = "A look at the audio features of the different albums of Kendrick Lamar (Hiphop)") +
  theme(plot.title = element_text(size = 19, hjust = 0.5),
        plot.subtitle = element_text(size = 10, hjust = 0.5))
```
