---
Author: Silva Patrick
---

```{r}
renv::activate()
```

```{r}
library(spotifyr)
library(tidyverse)
library(lubridate)
library(httpuv)
library(viridis)
library(fmsb)
library(ggradar2)
```

```{r}
Sys.setenv(SPOTIFY_CLIENT_ID = '50a6babd1746400f9de5a5a6ddf2b870')
Sys.setenv(SPOTIFY_CLIENT_SECRET = '290ce59c9b10458987bf608c2ee732bb')

authorization_code <- get_spotify_authorization_code(
                        scope = scopes()[c(4,7,8,9,10,14,15,17)])

theme_set(theme_minimal(base_size = 14))

data <- read_csv("../data/top_artists_with_audio_features.csv")
```

Audio Features are explained in this link:
https://help.spotontrack.com/article/what-do-the-audio-features-mean

```{r}
colnames(data)
```

How many songs does every artist have?

```{r}
data |>
  select(artist_name, track_name) |>
  distinct() |>
  group_by(artist_name) |>
  count(sort = TRUE)
```

How many songs are labelled under each genre?

```{r}
data |>
  select(artist_name, track_name, genres) |>
  distinct() |>
  group_by(genres) |>
  count(sort = TRUE)
```

How many artists are labelled under each genre?

```{r}
data |>
  select(artist_name, genres) |>
  distinct() |>
  group_by(genres) |>
  count(sort = TRUE)

genres_list <- data |>
  select(artist_name, genres) |>
  distinct() |>
  group_by(genres) |>
  count(sort = TRUE) |>
  filter(n > 1)
```

```{r}
data |>
  select(artist_name, popularity, genres) |>
  distinct() |>
  group_by(artist_name, popularity) |>
  count(sort = TRUE)
```

```{r}
data |>
  filter(artist_name == "Radiohead") |>
  mutate(loudness = -loudness) |>
  select(album_name, danceability, energy, key, mode, loudness, speechiness, acousticness,
         instrumentalness, liveness, valence, tempo, time_signature, duration_ms) |>
  group_by(album_name) |>
  summarize(across(everything(), list(mean = mean))) |>
  pivot_longer(cols = -album_name,
               names_to = c("feature", ".value"),
               names_pattern = "(.*)_(.*)") |>
  mutate(mean = log(mean)) |>
  ggplot(aes(x = feature, y = mean, color = album_name, group = album_name)) +
  geom_point() +
  geom_line() +
  facet_wrap(~album_name,  ncol=3) + 
  theme(legend.position = "none",
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank()) +
  labs(title = "Audio feature distributions across Radiohead's discography",
       y = NULL, x = NULL)
```

```{r}
data |>
  filter(artist_name == "Björk") |>
  mutate(loudness = -loudness) |>
  select(album_name, danceability, energy, key, mode, loudness, speechiness, acousticness,
         instrumentalness, liveness, valence, tempo, time_signature, duration_ms) |>
  group_by(album_name) |>
  summarize(across(everything(), list(mean = mean))) |>
  pivot_longer(cols = -album_name,
               names_to = c("feature", ".value"),
               names_pattern = "(.*)_(.*)") |>
  mutate(mean = log(mean)) |>
  ggplot(aes(x = feature, y = mean, color = album_name, group = album_name)) +
  geom_point() +
  geom_line() +
  facet_wrap(~album_name,  ncol=3) + 
  theme(legend.position = "none",
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank()) +
  labs(title = "Audio feature distributions across Björk's discography",
       y = NULL, x = NULL)
```

```{r}
data |>
  filter(artist_name == "Talking Heads") |>
  mutate(loudness = -loudness) |>
  select(album_name, danceability, energy, key, mode, loudness, speechiness, acousticness,
         instrumentalness, liveness, valence, tempo, time_signature, duration_ms) |>
  group_by(album_name) |>
  summarize(across(everything(), list(mean = mean))) |>
  pivot_longer(cols = -album_name,
               names_to = c("feature", ".value"),
               names_pattern = "(.*)_(.*)") |>
  mutate(mean = log(mean)) |>
  ggplot(aes(x = feature, y = mean, color = album_name, group = album_name)) +
  geom_point() +
  geom_line() +
  facet_wrap(~album_name,  ncol=3) + 
  theme(legend.position = "none",
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank()) +
  labs(title = "Audio feature distributions across Talking Heads' discography",
       y = NULL, x = NULL)
```

```{r}
data |>
  filter(artist_name == "JPEGMAFIA") |>
  mutate(loudness = -loudness) |>
  select(album_name, danceability, energy, key, mode, loudness, speechiness, acousticness,
         instrumentalness, liveness, valence, tempo, time_signature, duration_ms) |>
  group_by(album_name) |>
  summarize(across(everything(), list(mean = mean))) |>
  pivot_longer(cols = -album_name,
               names_to = c("feature", ".value"),
               names_pattern = "(.*)_(.*)") |>
  mutate(mean = log(mean)) |>
  ggplot(aes(x = feature, y = mean, color = album_name, group = album_name)) +
  geom_point() +
  geom_line() +
  facet_wrap(~album_name,  ncol=3) + 
  theme(legend.position = "none",
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        strip.background = element_blank(),
        strip.text.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank()) +
  labs(title = "Audio feature distributions across JPEGMAFIA's discography",
       y = NULL, x = NULL)
```

```{r}

```
